### ISSUE TITLE
shorebird cli should support windows

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#37]
Currently the shorebird tooling only works on MacOS (because of the shorebird engine).

**Todo**

- [x] build different versions of the shorebird engine for each platform/arch
- [x] pull the correct engine based on the host platform
- [x] proxy to Flutter with the correct args/paths

**Comment by eseidel** [comment]
This is blocked by #56 as it will be really hard to maintain multiple platforms w/o some form of automation.

**Comment by eseidel** [comment]
We believe linux now works, but need to test.  Windows is missing an installer.  Interesting to note that Rust doesn't use a curl | sh method on windows (perhaps there is no equivalent):
https://forge.rust-lang.org/infra/other-installation-methods.html

**Comment by eseidel** [comment]
The big thing missing from Windows is a `shorebird.bat` (or `shorebird.ps1`?) like Flutter's:
https://github.com/flutter/flutter/blob/master/bin/flutter.bat

**Comment by eseidel** [comment]
Filed https://github.com/shorebirdtech/install/issues/10 and https://github.com/shorebirdtech/install/issues/11

**Comment by eseidel** [comment]
Looking through shorebird_cli we have `runInShell` sprinkled in various places.  I suspect we need to centralize that handling (in part to deal with Windows).

**Comment by bryanoltman** [comment]
https://github.com/shorebirdtech/shorebird/pull/369 makes an already-installed shorebird work in powershell. I think the only remaining task is the installer.
